spring:
  datasource:
    url: jdbc:mysql://192.168.10.131:3306/glshop?&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
  dubbo:
    application:
      name: provider
      version: 1.0.1
    registry:
      address: zookeeper://192.168.10.121:2182?backup=192.168.10.121:2181,192.168.10.121:2183
    base-package: com.hk.hkmall.hkmalluser.service
    protocol:
      name: dubbo
      port: 20880

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true

dubbo:

server:
  port: 8088
